const fs = require('fs');

const items_841_894 = [
  // Page 166 (Chapter 7, Section 4: 副詞もおぼえよう！①)
  { page: 166, number: 841, word: "かならず", reading: "かならず", partOfSpeech: "副", meaning_vi: "nhất định", meaning_en: "absolutely, be sure to ~", example_ja: "宿題を 明日 かならず 持ってきて ください。", example_reading: "", example_en: "Please be sure to bring your homework tomorrow.", example_vi: "Nhất định ngày mai hãy đem bài tập đến." },
  { page: 166, number: 842, word: "きっと", reading: "きっと", partOfSpeech: "副", meaning_vi: "chắc chắn", meaning_en: "surely", example_ja: "がんばれば、きっと 合格できるでしょう。", example_reading: "", example_en: "If you do your best, I'm sure you'll pass.", example_vi: "Nếu cố gắng chắc chắn sẽ thi đậu." },
  { page: 166, number: 843, word: "しっかり［と］〈する〉", reading: "しっかり", partOfSpeech: "副", meaning_vi: "chắc, chắc chắn", meaning_en: "tightly, firmly, strongly", example_ja: "ポスターを しっかり はって ください。", example_reading: "", example_en: "Please hang the poster securely.", example_vi: "Hãy dán áp phích thật chắc." },
  { page: 166, number: 844, word: "きちんと〈する〉", reading: "きちんと", partOfSpeech: "副", meaning_vi: "đàng hoàng", meaning_en: "neatly, accurately", example_ja: "本は 本だなに きちんと 返して ください。", example_reading: "", example_en: "Please put the books back neatly on the bookshelf.", example_vi: "Hãy trả sách lại kệ sách đàng hoàng." },
  { page: 166, number: 845, word: "ちゃんと〈する〉", reading: "ちゃんと", partOfSpeech: "副", meaning_vi: "đàng hoàng", meaning_en: "properly", example_ja: "トイレを 出たら、ちゃんと 電気を 消しましょう。", example_reading: "", example_en: "Be sure to turn off the light when you leave the bathroom.", example_vi: "Ra khỏi nhà vệ sinh thì hãy tắt đèn đàng hoàng." },
  { page: 166, number: 846, word: "ぜったい［に］", reading: "ぜったい", partOfSpeech: "副", meaning_vi: "nhất định", meaning_en: "absolutely", example_ja: "明日の 試合は ぜったいに 勝ちたいです。", example_reading: "", example_en: "I absolutely want to win the match tomorrow.", example_vi: "Tôi nhất định muốn thắng trận đấu ngày mai." },
  { page: 166, number: 847, word: "ぜひ", reading: "ぜひ", partOfSpeech: "副", meaning_vi: "nhất định (làm gì đó)", meaning_en: "certainly, without fail", example_ja: "日本へ 来るときは ぜひ 私に れんらくして ください。", example_reading: "", example_en: "Please be certain to contact me when you come to Japan.", example_vi: "Khi đến Nhật, nhất định hãy liên lạc cho tôi." },

  // Page 167
  { page: 167, number: 848, word: "できるだけ", reading: "できるだけ", partOfSpeech: "副", meaning_vi: "trong khả năng có thể", meaning_en: "as much as possible", example_ja: "台風が 来ますから、できるだけ 早く 帰りましょう。", example_reading: "", example_en: "A typhoon is coming, so please try to go home as soon as possible.", example_vi: "Vì bão sẽ đến nên hãy về sớm trong khả năng có thể (càng sớm càng tốt)." },
  { page: 167, number: 849, word: "はっきり［と］〈する〉", reading: "はっきり", partOfSpeech: "副", meaning_vi: "rõ ràng", meaning_en: "clearly", example_ja: "晴れた 日は 富士山が はっきり 見えます。", example_reading: "", example_en: "On clear days, Mt. Fuji can be seen clearly.", example_vi: "Ngày nắng đẹp sẽ thấy rõ núi Phú Sỹ." },
  { page: 167, number: 850, word: "ずいぶん［と］", reading: "ずいぶん", partOfSpeech: "副", meaning_vi: "nhiều", meaning_en: "fairly, quite", example_ja: "ずいぶん 日本語が 上手に なりましたね。", example_reading: "", example_en: "You've gotten quite good at Japanese.", example_vi: "Tiếng Nhật đã giỏi lên nhiều nhỉ." },
  { page: 167, number: 851, word: "かなり", reading: "かなり", partOfSpeech: "副", meaning_vi: "khá là", meaning_en: "pretty, quite", example_ja: "あの フランス料理の 店は かなり 高そうです。", example_reading: "", example_en: "That French restaurant looks pretty expensive.", example_vi: "Tiệm ăn Pháp đó có vẻ khá là đắt." },
  { page: 167, number: 852, word: "だいぶ", reading: "だいぶ", partOfSpeech: "副", meaning_vi: "nhiều", meaning_en: "largely", example_ja: "日本人の 考え方が だいぶ わかって きました。", example_reading: "", example_en: "I've come to largely understand the Japanese people's way of thinking.", example_vi: "Tôi đã phần nào hiểu ra nhiều cách suy nghĩ của người Nhật." },
  { page: 167, number: 853, word: "もっと", reading: "もっと", partOfSpeech: "副", meaning_vi: "hơn nữa", meaning_en: "more, ~er", example_ja: "もっと がんばらないと、合格できませんよ。", example_reading: "", example_en: "You won't be able to pass if you don't try harder.", example_vi: "Nếu không cố gắng hơn nữa thì không thể thi đậu đâu đấy." },

  // Page 168
  { page: 168, number: 854, word: "だいたい", reading: "だいたい", partOfSpeech: "副", meaning_vi: "đại khái, gần như, hầu như", meaning_en: "mostly", example_ja: "レポートは だいたい 終わりました。", example_reading: "", example_en: "The report is mostly finished.", example_vi: "Bài báo cáo đại khái đã xong." },
  { page: 168, number: 855, word: "たいてい", reading: "たいてい", partOfSpeech: "副", meaning_vi: "gần như, hầu như", meaning_en: "usually", example_ja: "休みの 日は たいてい 家に います。", example_reading: "", example_en: "On my days off, I usually stay at home.", example_vi: "Ngày nghỉ tôi hầu như ở nhà." },
  { page: 168, number: 856, word: "たまに", reading: "たまに", partOfSpeech: "副", meaning_vi: "đôi khi", meaning_en: "occasionally", example_ja: "たまに 近所の レストランへ 行きます。", example_reading: "", example_en: "Occasionally, I go to restaurants in the neighborhood.", example_vi: "Đôi khi tôi đi nhà hàng gần nhà." },
  { page: 168, number: 857, word: "ぜんぜん", reading: "ぜんぜん", partOfSpeech: "副", meaning_vi: "hoàn toàn (không)", meaning_en: "(not) at all, completely", example_ja: "日本語の ニュースが ぜんぜん わかりませんでした。", example_reading: "", example_en: "I don't understand Japanese news at all.", example_vi: "Tôi đã hoàn toàn không hiểu tin tức tiếng Nhật." },
  { page: 168, number: 858, word: "けっして", reading: "けっして", partOfSpeech: "副", meaning_vi: "nhất định (không)", meaning_en: "never, absolutely (not)", example_ja: "この 絵には けっして さわらないで ください。", example_reading: "", example_en: "Please don't ever touch this painting.", example_vi: "Nhất định xin đừng rờ vào bức tranh này." },
  { page: 168, number: 859, word: "ちっとも", reading: "ちっとも", partOfSpeech: "副", meaning_vi: "một chút cũng (không)", meaning_en: "not even a little", example_ja: "日本語の ニュースは ちっとも わかりません。", example_reading: "", example_en: "I don't understand Japanese news even a little bit.", example_vi: "Tôi chẳng hiểu tí gì tin tức tiếng Nhật." },
  { page: 168, number: 860, word: "まだ", reading: "まだ", partOfSpeech: "副", meaning_vi: "vẫn còn, vẫn chưa", meaning_en: "still, (not) yet", example_ja: "①この 辞書は まだ 使って います。\n②私は まだ 昼ごはんを 食べて いません。", example_reading: "", example_en: "① I'm still using this dictionary.\n② I haven't eaten lunch yet.", example_vi: "① Tôi vẫn còn sử dụng quyển tự điển này.\n② Tôi vẫn chưa ăn cơm trưa." },
  { page: 168, number: 861, word: "ほとんど", reading: "ほとんど", partOfSpeech: "副", meaning_vi: "hầu như, hầu hết", meaning_en: "mostly", example_ja: "漢字を 勉強したのに、ほとんど わすれました。", example_reading: "", example_en: "Even though I studied kanji, I've mostly forgotten it.", example_vi: "Tôi đã học chữ Kanji vậy mà quên hầu hết." },

  // Page 169
  { page: 169, number: 862, word: "なかなか", reading: "なかなか", partOfSpeech: "副", meaning_vi: "mãi vẫn (không)", meaning_en: "considerably, rather, (not) really", example_ja: "雪で バスが なかなか 来ません。", example_reading: "", example_en: "Buses aren't really running due to the snow.", example_vi: "Vì trời tuyết nên xe buýt mãi không đến." },

  // Page 170 (Section 5: 副詞もおぼえよう！②)
  { page: 170, number: 863, word: "急に", reading: "きゅうに", partOfSpeech: "副", meaning_vi: "đột ngột, thình lình, bất ngờ", meaning_en: "suddenly", example_ja: "午後 急に 空が 暗く なりました。", example_reading: "", example_en: "The sky suddenly got dark in the afternoon.", example_vi: "Buổi chiều trời đột ngột trở tối." },
  { page: 170, number: 864, word: "しばらく", reading: "しばらく", partOfSpeech: "副", meaning_vi: "một lúc, một chút", meaning_en: "for a while, for a bit", example_ja: "しばらく お待ちください。", example_reading: "", example_en: "Please wait for a bit.", example_vi: "Vui lòng chờ cho một chút." },
  { page: 170, number: 865, word: "ずっと", reading: "ずっと", partOfSpeech: "副", meaning_vi: "suốt, luôn, hẳn", meaning_en: "continuously, for a long time", example_ja: "①ずっと 日本へ 留学したいと 思って いました。\n②妹は 私より ずっと 頭が いいです。", example_reading: "", example_en: "① I had always wanted to go on an exchange to Japan.\n② My younger sister is much smarter than I am.", example_vi: "① Tôi đã muốn du học Nhật Bản lâu nay.\n② Chị tôi thông minh hơn hẳn tôi." },
  { page: 170, number: 866, word: "そのまま", reading: "そのまま", partOfSpeech: "副", meaning_vi: "cứ như thế", meaning_en: "as is, just like that", example_ja: "ぬいだ コートが そのまま 置いて あります。", example_reading: "", example_en: "The coat I took off is still lying just as I left it.", example_vi: "Chiếc áo choàng cởi ra vẫn được để nguyên như thế." },
  { page: 170, number: 867, word: "そろそろ", reading: "そろそろ", partOfSpeech: "副", meaning_vi: "sắp sửa, chuẩn bị (chỉ thời gian)", meaning_en: "soon", example_ja: "もう ９時ですから、そろそろ 帰ります。", example_reading: "", example_en: "It's already 9:00, so I'm going home soon.", example_vi: "Đã 9 giờ rồi nên tôi chuẩn bị về." },
  { page: 170, number: 868, word: "とうとう", reading: "とうとう", partOfSpeech: "副", meaning_vi: "cuối cùng", meaning_en: "finally, ultimately", example_ja: "あの 二人は よく けんかして いましたが、とうとう 別れて しまいました。", example_reading: "", example_en: "Those two fight often, and they've finally broken up.", example_vi: "Hai người đó thường cãi nhau và cuối cùng đã chia tay mất rồi." },

  // Page 171
  { page: 171, number: 869, word: "やっと", reading: "やっと", partOfSpeech: "副", meaning_vi: "cuối cùng (đạt được)", meaning_en: "at last, finally", example_ja: "結婚したい 人に やっと 会えました。", example_reading: "", example_en: "I finally met someone I want to marry.", example_vi: "Cuối cùng tôi đã gặp được người mình muốn kết hôn." },
  { page: 171, number: 870, word: "たしか", reading: "たしか", partOfSpeech: "副", meaning_vi: "đúng là", meaning_en: "certainly, surely", example_ja: "明日の 会議は たしか ３時からだと 思います。", example_reading: "", example_en: "I'm sure the meeting tomorrow starts at 3:00.", example_vi: "Tôi nhớ đúng là buổi họp ngày mai bắt đầu từ 3 giờ." },
  { page: 171, number: 871, word: "どうも", reading: "どうも", partOfSpeech: "副", meaning_vi: "có vẻ, xem ra, hình như", meaning_en: "somehow, seemingly", example_ja: "兄は どうも うれしい ことが あった ようです。", example_reading: "", example_en: "It would seem that something good has happened to my brother.", example_vi: "Hình như anh tôi có chuyện vui." },
  { page: 171, number: 872, word: "たとえば", reading: "たとえば", partOfSpeech: "副", meaning_vi: "ví dụ", meaning_en: "for example", example_ja: "お正月に アジア、たとえば タイに 行きたいです。", example_reading: "", example_en: "During New Year's, I want to travel somewhere in Asia, like Thailand for example.", example_vi: "Ngày Tết, tôi muốn đi châu Á, ví dụ Thái Lan." },
  { page: 171, number: 873, word: "直接", reading: "ちょくせつ", partOfSpeech: "副", meaning_vi: "trực tiếp", meaning_en: "direct", example_ja: "あなたから 直接 彼女に 話して ください。", example_reading: "", example_en: "Please talk to her yourself directly.", example_vi: "Bạn hãy nói chuyện trực tiếp với cô ấy." },
  { page: 171, number: 874, word: "特に", reading: "とくに", partOfSpeech: "副", meaning_vi: "đặc biệt", meaning_en: "especially", example_ja: "あまい 物の 中で、特に ケーキが 大好きです。", example_reading: "", example_en: "Among sweet things, I especially love cakes.", example_vi: "Trong các món ngọt, đặc biệt tôi rất thích bánh kem." },
  { page: 171, number: 875, word: "どんどん", reading: "どんどん", partOfSpeech: "副", meaning_vi: "dần dần, đều", meaning_en: "steadily, rapidly", example_ja: "留学生が どんどん ふえて います。", example_reading: "", example_en: "The number of exchange students is steadily increasing.", example_vi: "Du học sinh dần dần tăng lên." },

  // Page 172
  { page: 172, number: 876, word: "なるほど", reading: "なるほど", partOfSpeech: "副", meaning_vi: "thì ra là vậy", meaning_en: "I see", example_ja: "A「この 本は 練習問題も あって、いいですよ。」\nB「なるほど。よさそうですね。」", example_reading: "", example_en: "A: This book is good because it also has practice questions.\nB: I see. That does look good.", example_vi: "A: Quyển sách này có bài luyện tập nên tốt đấy.\nB: Ra là vậy, có vẻ tốt nhỉ." },
  { page: 172, number: 877, word: "はじめて", reading: "はじめて", partOfSpeech: "副", meaning_vi: "lần đầu tiên", meaning_en: "first, for the first time", example_ja: "先月 はじめて、北海道へ 行くことが できました。", example_reading: "", example_en: "I was able to go to Hokkaido for the first time last month.", example_vi: "Tháng trước lần đầu tiên tôi được đi Hokkaido." },
  { page: 172, number: 878, word: "はじめに", reading: "はじめに", partOfSpeech: "副", meaning_vi: "đầu tiên, trước tiên", meaning_en: "at first, first", example_ja: "はじめに にんじんを 細かく 切って ください。", example_reading: "", example_en: "First, please finely chop the carrots.", example_vi: "Trước tiên hãy cắt nhỏ cà rốt." },
  { page: 172, number: 879, word: "もし", reading: "もし", partOfSpeech: "副", meaning_vi: "nếu", meaning_en: "if, in the event of ~", example_ja: "もし 時間が あったら、ランチを しませんか。", example_reading: "", example_en: "If you have time, would you like to get lunch?", example_vi: "Nếu có thời gian, đi dùng bữa trưa nhé." },
  { page: 172, number: 880, word: "もちろん", reading: "もちろん", partOfSpeech: "副", meaning_vi: "đương nhiên", meaning_en: "of course", example_ja: "結婚式に 招待されたら、もちろん 出席したいです。", example_reading: "", example_en: "If I'm invited to the wedding, I would of course like to attend.", example_vi: "Nếu được mời dự lễ kết hôn, đương nhiên tôi muốn tham dự." },
  { page: 172, number: 881, word: "やはり", reading: "やはり", partOfSpeech: "副", meaning_vi: "như dự đoán, đúng là", meaning_en: "as expected", example_ja: "きのうの 試合は やはり Aチームが 勝ちましたね。", example_reading: "", example_en: "As expected, Team A won the match yesterday.", example_vi: "Trận đấu hôm qua đúng như dự đoán đội A đã thắng nhỉ." },
  { page: 172, number: 882, word: "実は", reading: "じつは", partOfSpeech: "副", meaning_vi: "thật ra", meaning_en: "actually, the truth is ~", example_ja: "実は 来月、帰国する ことに なりました。", example_reading: "", example_en: "Actually, I'll be going back to my country next month.", example_vi: "Thật ra tháng tới tôi về nước." },

  // Page 173
  { page: 173, number: 883, word: "いかが", reading: "いかが", partOfSpeech: "副", meaning_vi: "thế nào, thì sao (cách hỏi lịch sự)", meaning_en: "how", example_ja: "コーヒーは いかがですか。", example_reading: "", example_en: "How would you like some coffee?", example_vi: "Anh/chị uống cà phê chứ?" },
  { page: 173, number: 884, word: "いっしょうけんめい〈な〉", reading: "いっしょうけんめい", partOfSpeech: "名/ナ形", meaning_vi: "sự cố gắng hết sức mình, sự nỗ lực (cố gắng hết mình, nỗ lực)", meaning_en: "to one's best ability/ with all one's might", example_ja: "毎日 いっしょうけんめい（に）勉強して います。(ナ形)", example_reading: "", example_en: "I study as best as I can everyday.", example_vi: "Hàng ngày tôi cố gắng học tập hết sức mình." },
  { page: 173, number: 885, word: "おおぜい", reading: "おおぜい", partOfSpeech: "名", meaning_vi: "sự đông đảo", meaning_en: "a great number of (something)", example_ja: "この 海は 有名で、人が おおぜい 来ます。", example_reading: "", example_en: "This beach is famous, so many people come here.", example_vi: "Biển này nổi tiếng nên nhiều người đến." },

  // Page 174 (Section 6: 接続詞もおぼえよう！)
  { page: 174, number: 886, word: "だから", reading: "だから", partOfSpeech: "接続", meaning_vi: "vì vậy", meaning_en: "therefore", example_ja: "子どもが 大好きです。だから、ようち園の 先生に なりたいです。", example_reading: "", example_en: "I love children. Therefore, I want to be a kindergarten teacher.", example_vi: "Tôi rất thích trẻ con. Vì vậy, tôi muốn trở thành giáo viên mẫu giáo." },
  { page: 174, number: 887, word: "それで", reading: "それで", partOfSpeech: "接続", meaning_vi: "vì vậy", meaning_en: "then, so", example_ja: "きのうは 熱が ありました。それで、学校を 休みました。", example_reading: "", example_en: "I had a fever yesterday. So, I took the day off from school.", example_vi: "Hôm qua tôi bị sốt. Vì vậy, tôi đã nghỉ học." },
  { page: 174, number: 888, word: "または", reading: "または", partOfSpeech: "接続", meaning_vi: "hoặc là, hay", meaning_en: "also, or", example_ja: "電話 または メールで れんらくして ください。", example_reading: "", example_en: "Please contact me by phone or e-mail.", example_vi: "Hãy liên lạc bằng điện thoại hay e-mail." },
  { page: 174, number: 889, word: "それに", reading: "それに", partOfSpeech: "接続", meaning_vi: "ngoài ra, đã vậy", meaning_en: "besides", example_ja: "連休は ホテル代が 高いです。それに、どこも 人が 多いです。", example_reading: "", example_en: "Hotel fairs are expensive during extended weekends. Besides, it's crowded no matter where you go.", example_vi: "Kỳ nghỉ nhiều ngày liên tục thì tiền khách sạn mắc. Đã vậy chỗ nào cũng đông người." },

  // Page 175
  { page: 175, number: 890, word: "そのうえ", reading: "そのうえ", partOfSpeech: "接続", meaning_vi: "ngoài ra, còn nữa, lại còn", meaning_en: "furthermore, in addition", example_ja: "彼は ハンサムです。そのうえ、とても お金持ちです。", example_reading: "", example_en: "He's handsome. Furthermore, he's very rich.", example_vi: "Anh ấy đẹp trai. Lại còn rất giàu có." },
  { page: 175, number: 891, word: "すると", reading: "すると", partOfSpeech: "接続", meaning_vi: "thế là, thế rồi", meaning_en: "in such case, then", example_ja: "空が 急に 暗く なりました。すると、大雨が 降って きました。", example_reading: "", example_en: "The sky suddenly got dark. Then, it started raining heavily.", example_vi: "Bầu trời đột nhiên trở nên tối. Thế rồi, cơn mưa lớn ào đến." },
  { page: 175, number: 892, word: "けれども", reading: "けれども", partOfSpeech: "接続", meaning_vi: "nhưng, tuy nhiên", meaning_en: "however, but", example_ja: "日本は 住みやすいです。けれども、物価が 高いです。", example_reading: "", example_en: "Japan is an easy place to live. But the cost of living is high.", example_vi: "Nhật Bản dễ sống. Nhưng vật giá đắt đỏ." },
  { page: 175, number: 893, word: "それなら", reading: "それなら", partOfSpeech: "接続", meaning_vi: "nếu vậy, vậy thì", meaning_en: "then, if so, then ~", example_ja: "A「日本に 来たのは はじめてなんです。」\nB「それなら、東京を 案内しますよ。」", example_reading: "", example_en: "A: This is my first time coming to Japan.\nB: Then let me show you around Tokyo.", example_vi: "A: Đây là lần đầu tiên tôi đến Nhật.\nB: Nếu vậy, để tôi hướng dẫn (giới thiệu) Tokyo cho nhé." },

  // Page 176
  { page: 176, number: 894, word: "ところで", reading: "ところで", partOfSpeech: "接続", meaning_vi: "nhưng này, à này, mà này", meaning_en: "by the way", example_ja: "A「きのうの 雨は すごかったですね。」\nB「ええ。ところで、明日の 夜は ひまですか。」", example_reading: "", example_en: "A: The rain yesterday was terrible.\nB: Yeah. By the way, are you free tomorrow night?", example_vi: "A: Cơn mưa hôm qua thật lớn nhỉ.\nB: Vâng. Mà này, tối mai bạn rảnh không?" }
];

fs.writeFileSync('scripts/items_part_d.json', JSON.stringify(items_841_894, null, 2));
console.log('Saved items_part_d.json with', items_841_894.length, 'items');
