const fs = require('fs');

const items_717_781 = [
  // Page 143 (Section 3: ファッション)
  { page: 143, number: 717, word: "スーツ", reading: "スーツ", partOfSpeech: "名", meaning_vi: "trang phục vét", meaning_en: "suit", example_ja: "毎日、スーツを着て、会社に行きます。", example_reading: "", example_en: "I wear a suit to work every day.", example_vi: "Hàng ngày tôi mặc vét đi đến công ty. (đi làm)" },
  { page: 143, number: 718, word: "着物", reading: "きもの", partOfSpeech: "名", meaning_vi: "kimono", meaning_en: "kimono", example_ja: "成人式には たくさんの 人が 着物を 着ます。", example_reading: "", example_en: "Many people wear kimono to the Coming-of-age Ceremony.", example_vi: "Trong lễ thành nhân, có nhiều người mặc kimono." },
  { page: 143, number: 719, word: "くつ下", reading: "くつした", partOfSpeech: "名", meaning_vi: "vớ", meaning_en: "sock", example_ja: "冬は くつ下を はいて 寝ます。", example_reading: "", example_en: "I sleep with my socks on in the winter.", example_vi: "Mùa đông tôi mang vớ đi ngủ." },
  { page: 143, number: 720, word: "下着", reading: "したぎ", partOfSpeech: "名", meaning_vi: "đồ lót", meaning_en: "underwear", example_ja: "旅行の バッグに 下着を 入れました。", example_reading: "", example_en: "I put underwear in my bag for my trip.", example_vi: "Tôi cho đồ lót vào túi du lịch." },
  { page: 143, number: 721, word: "手ぶくろ", reading: "てぶくろ", partOfSpeech: "名", meaning_vi: "găng tay", meaning_en: "glove", example_ja: "冬は 手ぶくろを して、出かけます。", example_reading: "", example_en: "In the winter, I wear gloves when I go out.", example_vi: "Mùa đông tôi đeo găng tay đi ra ngoài." },
  { page: 143, number: 722, word: "指輪", reading: "ゆびわ", partOfSpeech: "名", meaning_vi: "nhẫn", meaning_en: "ring", example_ja: "これは 母から もらった 指輪です。", example_reading: "", example_en: "This is a ring I got from my mother.", example_vi: "Đây là chiếc nhẫn mẹ tôi cho tôi." },

  // Page 144
  { page: 144, number: 723, word: "サンダル", reading: "サンダル", partOfSpeech: "名", meaning_vi: "giày xăng-đan", meaning_en: "sandals", example_ja: "歩きやすい サンダルを さがしています。", example_reading: "", example_en: "I'm looking for some sandals that are easy to walk in.", example_vi: "Tôi đang tìm đôi giày xăng-đan dễ mang." },
  { page: 144, number: 724, word: "リュック", reading: "リュック", partOfSpeech: "名", meaning_vi: "ba lô", meaning_en: "backpack", example_ja: "この リュックには 教科書が たくさん 入っています。", example_reading: "", example_en: "There are a lot of textbooks in this backpack.", example_vi: "Trong ba lô này có nhiều sách giáo khoa." },
  { page: 144, number: 725, word: "アクセサリー", reading: "アクセサリー", partOfSpeech: "名", meaning_vi: "đồ trang sức", meaning_en: "accessory", example_ja: "仕事の ときは アクセサリーを しません。", example_reading: "", example_en: "I don't wear any accessories at work.", example_vi: "Khi làm việc không đeo đồ trang sức." },
  { page: 144, number: 726, word: "ポケット", reading: "ポケット", partOfSpeech: "名", meaning_vi: "túi, ngăn", meaning_en: "pocket", example_ja: "この バッグは ポケットが 多いです。", example_reading: "", example_en: "This bag has a lot of pockets.", example_vi: "Giỏ xách này có nhiều ngăn." },
  { page: 144, number: 727, word: "ひも", reading: "ひも", partOfSpeech: "名", meaning_vi: "dây", meaning_en: "string, lace", example_ja: "この くつの ひもは きれいです。", example_reading: "", example_en: "These shoelaces are pretty.", example_vi: "Dây đôi giày này đẹp." },
  { page: 144, number: 728, word: "髪型", reading: "かみがた", partOfSpeech: "名", meaning_vi: "kiểu tóc", meaning_en: "hairstyle", example_ja: "どんな 髪型が 好きですか。", example_reading: "", example_en: "What kind of hairstyle do you like?", example_vi: "Bạn thích kiểu tóc như thế nào?" },
  { page: 144, number: 729, word: "美容院", reading: "びよういん", partOfSpeech: "名", meaning_vi: "tiệm cắt (uốn) tóc", meaning_en: "hair salon", example_ja: "あの 美容院は とても 高いです。", example_reading: "", example_en: "That hair salon is very expensive.", example_vi: "Tiệm cắt tóc đó rất mắc." },
  { page: 144, number: 730, word: "カット〈する〉", reading: "カット", partOfSpeech: "名", meaning_vi: "việc cắt (thường chỉ việc cắt tóc)", meaning_en: "cut", example_ja: "いつも あの 美容院で カットして います。", example_reading: "", example_en: "I always get my hair cut at that hair salon.", example_vi: "Tôi luôn cắt tóc ở tiệm cắt tóc đó." },

  // Page 145
  { page: 145, number: 731, word: "かがみ", reading: "かがみ", partOfSpeech: "名", meaning_vi: "gương", meaning_en: "mirror", example_ja: "出かける前に かがみで チェックします。", example_reading: "", example_en: "I check myself in the mirror before I go out.", example_vi: "Trước khi ra ngoài, kiểm tra qua gương soi." },
  { page: 145, number: 732, word: "かっこいい", reading: "かっこいい", partOfSpeech: "イ形", meaning_vi: "phong độ, đẹp, ngầu", meaning_en: "cool", example_ja: "かっこいい ヘアスタイルに したいです。", example_reading: "", example_en: "I want to have a cool hairstyle.", example_vi: "Tôi muốn kiểu tóc đẹp." },
  { page: 145, number: 733, word: "かわいい", reading: "かわいい", partOfSpeech: "イ形", meaning_vi: "dễ thương", meaning_en: "cute", example_ja: "妹は かわいい 服が 大好きです。", example_reading: "", example_en: "My younger sister loves cute clothes.", example_vi: "Chị tôi rất thích trang phục dễ thương." },
  { page: 145, number: 734, word: "ちょうどいい", reading: "ちょうどいい", partOfSpeech: "イ形", meaning_vi: "vừa vặn, vừa phải, vừa đẹp", meaning_en: "just right, just enough", example_ja: "この バッグは ちょうどいい サイズです。", example_reading: "", example_en: "This bag is just the right size.", example_vi: "Túi xách này có kích cỡ vừa phải." },

  // Page 146 (Section 4: ようす①)
  { page: 146, number: 735, word: "ようす", reading: "ようす", partOfSpeech: "名", meaning_vi: "tình hình, trạng thái", meaning_en: "appearance, situation, condition", example_ja: "暗くて、外の ようすが よく わかりません。", example_reading: "", example_en: "It so dark I can't see the conditions outside.", example_vi: "Tối quá nên tôi không rõ tình hình bên ngoài." },
  { page: 146, number: 736, word: "形", reading: "かたち", partOfSpeech: "名", meaning_vi: "hình thức, hình dạng", meaning_en: "shape", example_ja: "この クッキーは 星の 形です。", example_reading: "", example_en: "This cookie is in the shape of a star.", example_vi: "Bánh quy này hình ngôi sao." },
  { page: 146, number: 737, word: "倍", reading: "ばい", partOfSpeech: "名", meaning_vi: "gấp (hai)", meaning_en: "~ times, double, twice as ~", example_ja: "これは あの ケーキの ２倍の ねだんです。", example_reading: "", example_en: "This is twice the cost of that cake.", example_vi: "Cái này có giá gấp đôi cái bánh kem kia." },
  { page: 146, number: 738, word: "以上", reading: "いじょう", partOfSpeech: "名", meaning_vi: "trở lên", meaning_en: "~ or more", example_ja: "夏は 30度以上の 日が 何日も あります。", example_reading: "", example_en: "There were several days in the summer that were 30 degrees Celsius or more.", example_vi: "Mùa hè có nhiều ngày 30°C trở lên." },
  { page: 146, number: 739, word: "以下", reading: "いか", partOfSpeech: "名", meaning_vi: "trở xuống, dưới~", meaning_en: "~ or less", example_ja: "漢字の テストは いつも 50点以下です。", example_reading: "", example_en: "I always get 50 points or less on kanji tests.", example_vi: "Bài kiểm tra Kanji lúc nào cũng dưới 50 điểm." },
  { page: 146, number: 740, word: "以内", reading: "いない", partOfSpeech: "名", meaning_vi: "trong vòng", meaning_en: "within, under", example_ja: "２万円以内の 時計を 買いたいです。", example_reading: "", example_en: "I want to buy a watch for under 20,000 yen.", example_vi: "Tôi muốn mua đồng hồ trong vòng 20 000 yên." },
  { page: 146, number: 741, word: "以外", reading: "いがい", partOfSpeech: "名", meaning_vi: "ngoài (~) ra, ngoại trừ", meaning_en: "outside of, except for", example_ja: "来週の 旅行は 兄以外 みんな 行けます。", example_reading: "", example_en: "Everyone is going on the trip next week except for my older brother.", example_vi: "Chuyến du lịch tuần sau mọi người đều có thể đi ngoại trừ anh tôi." },

  // Page 147
  { page: 147, number: 742, word: "両方", reading: "りょうほう", partOfSpeech: "名", meaning_vi: "cả hai", meaning_en: "both", example_ja: "この 赤と 青の シャツを 両方 買いました。", example_reading: "", example_en: "I'll both this red shirt and this blue shirt.", example_vi: "Tôi đã mua cả hai cái áo màu đỏ và màu xanh này." },
  { page: 147, number: 743, word: "ひま〈な〉", reading: "ひま", partOfSpeech: "名/ナ形", meaning_vi: "giờ rảnh (rảnh rỗi)", meaning_en: "leisure, free time/free, available", example_ja: "いそがしくて、遊ぶ ひまが ありません。(名)\nひまな ときは 本を 読んでいます。(ナ形)", example_reading: "", example_en: "I'm so busy, I don't have any free time to play.\nIn my free time, I read books.", example_vi: "Tôi bận rộn nên không có thời gian rảnh để chơi.\nKhi rảnh rỗi, tôi đọc sách." },
  { page: 147, number: 744, word: "ふつう〈な〉", reading: "ふつう", partOfSpeech: "名/ナ形", meaning_vi: "sự bình thường (bình thường)", meaning_en: "normality, regular/ normal, regular, average", example_ja: "ふつうの 毎日が 楽しいです。(名)\nあの 店は 料理も サービスも ふつうです。(ナ形)", example_reading: "", example_en: "I enjoy every normal day.\nThe food and the service at that restaurant is average.", example_vi: "Tôi thấy vui với mỗi ngày bình thường.\nTiệm đó cả món ăn lẫn phục vụ đều bình thường." },
  { page: 147, number: 745, word: "自由〈な〉", reading: "じゆう", partOfSpeech: "名/ナ形", meaning_vi: "sự tự do (tự do)", meaning_en: "freedom/free", example_ja: "おとなに なったら、自由が ほしいです。(名)\n日本の 生活は とても 自由です。(ナ形)", example_reading: "", example_en: "When I become an adult, I want freedom.\nLive in Japan is very free.", example_vi: "Nếu thành người lớn, tôi muốn có tự do.\nCuộc sống ở Nhật rất tự do." },
  { page: 147, number: 746, word: "ていねいな", reading: "ていねいな", partOfSpeech: "ナ形", meaning_vi: "cẩn thận, lịch sự", meaning_en: "polite, courteous", example_ja: "先生から ていねいな メールを いただきました。", example_reading: "", example_en: "I got a courteous letter from my teacher.", example_vi: "Tôi đã nhận e-mail lịch sự từ giáo viên." },

  // Page 148
  { page: 148, number: 747, word: "大きな", reading: "おおきな", partOfSpeech: "連体", meaning_vi: "to lớn", meaning_en: "big, large", example_ja: "家の 前に 大きな 木が あります。", example_reading: "", example_en: "There is a large tree in front of the house.", example_vi: "Trước nhà có một cái cây to." },
  { page: 148, number: 748, word: "小さな", reading: "ちいさな", partOfSpeech: "連体", meaning_vi: "nhỏ", meaning_en: "small, little", example_ja: "庭に 小さな 花が 咲いています。", example_reading: "", example_en: "The small flowers in the garden are in bloom.", example_vi: "Trong vườn những bông hoa nhỏ nở." },
  { page: 148, number: 749, word: "へんな", reading: "へんな", partOfSpeech: "ナ形", meaning_vi: "kỳ lạ, kỳ quặc", meaning_en: "strange", example_ja: "妹は へんな ファッションが 好きです。", example_reading: "", example_en: "My younger sister likes strange fashion.", example_vi: "Chị tôi thích thời trang kỳ quặc." },
  { page: 148, number: 750, word: "じゅうぶんな", reading: "じゅうぶんな", partOfSpeech: "ナ形", meaning_vi: "đầy đủ, tốt", meaning_en: "sufficient, satisfactory", example_ja: "これが できたら、N4の 勉強は じゅうぶんです。", example_reading: "", example_en: "If I can do this, my studying for the N4 will be sufficient.", example_vi: "Nếu làm được bài này thì việc học N4 khá đầy đủ." },

  // Page 149 (Section 5: ようす②)
  { page: 149, number: 751, word: "美しい", reading: "うつくしい", partOfSpeech: "イ形", meaning_vi: "đẹp", meaning_en: "beautiful", example_ja: "こんなに 美しい 景色を 見たことが ありません。", example_reading: "", example_en: "I've never seen such beautiful scenery.", example_vi: "Tôi chưa từng thấy phong cảnh đẹp như thế này." },
  { page: 149, number: 752, word: "きたない", reading: "きたない", partOfSpeech: "イ形", meaning_vi: "dơ, bẩn", meaning_en: "dirty, messy", example_ja: "兄の 部屋は とても きたないです。", example_reading: "", example_en: "My older brother's room is really messy.", example_vi: "Phòng của anh tôi rất bẩn." },
  { page: 149, number: 753, word: "うまい", reading: "うまい", partOfSpeech: "イ形", meaning_vi: "giỏi", meaning_en: "skillful", example_ja: "彼は サッカーも 野球も とても うまいです。", example_reading: "", example_en: "He's good at soccer and baseball.", example_vi: "Anh ấy rất giỏi đá bóng lẫn bóng chày." },
  { page: 149, number: 754, word: "やわらかい", reading: "やわらかい", partOfSpeech: "イ形", meaning_vi: "mềm, mềm mại", meaning_en: "soft, flexible", example_ja: "新しい ソファーは とても やわらかいです。", example_reading: "", example_en: "The new sofa is really soft.", example_vi: "Bộ sofa mới rất mềm mại." },
  { page: 149, number: 755, word: "かたい", reading: "かたい", partOfSpeech: "イ形", meaning_vi: "cứng", meaning_en: "hard, stiff", example_ja: "この パンは かたいですが、おいしいです。", example_reading: "", example_en: "This bread is hard, but delicious.", example_vi: "Bánh mì này cứng nhưng ngon." },
  { page: 149, number: 756, word: "くわしい", reading: "くわしい", partOfSpeech: "イ形", meaning_vi: "chi tiết, cụ thể", meaning_en: "detailed, well-informed", example_ja: "この 辞書の 説明は くわしいです。", example_reading: "", example_en: "The explanations in this dictionary are detailed.", example_vi: "Phần giải thích của cuốn tự điển này chi tiết." },
  { page: 149, number: 757, word: "細かい", reading: "こまかい", partOfSpeech: "イ形", meaning_vi: "nhỏ, chi tiết, chi li", meaning_en: "fine, minute", example_ja: "玉ねぎを 細かく 切って ください。", example_reading: "", example_en: "Please cut the onions finely.", example_vi: "Hãy cắt hành tây thật nhỏ." },

  // Page 150
  { page: 150, number: 758, word: "怖い", reading: "こわい", partOfSpeech: "イ形", meaning_vi: "sợ", meaning_en: "scary, fearful", example_ja: "この 道は 夜に なると、暗くて 怖いです。", example_reading: "", example_en: "This road gets dark and scary at night.", example_vi: "Con đường này khi về đêm thì tối nên tôi sợ." },
  { page: 150, number: 759, word: "すごい", reading: "すごい", partOfSpeech: "イ形", meaning_vi: "tuyệt, giỏi, lớn", meaning_en: "amazing, dreadful", example_ja: "きのうの 夜は すごい 雨でした。", example_reading: "", example_en: "The rain last night was dreadful.", example_vi: "Tối hôm qua mưa rất lớn." },
  { page: 150, number: 760, word: "すばらしい", reading: "すばらしい", partOfSpeech: "イ形", meaning_vi: "tuyệt vời", meaning_en: "magnificent", example_ja: "留学で すばらしい 経験が できました。", example_reading: "", example_en: "I was able to have some amazing experiences on my exchange.", example_vi: "Tôi có được kinh nghiệm tuyệt vời nhờ du học." },
  { page: 150, number: 761, word: "正しい", reading: "ただしい", partOfSpeech: "イ形", meaning_vi: "đúng, chính xác", meaning_en: "correct", example_ja: "この 答えが 正しいか どうか わかりません。", example_reading: "", example_en: "I don't know if this answer is correct or not.", example_vi: "Tôi không biết câu trả lời này có chính xác hay không." },
  { page: 150, number: 762, word: "ひどい", reading: "ひどい", partOfSpeech: "イ形", meaning_vi: "ghê, tồi tệ", meaning_en: "terrible", example_ja: "きのうの テストは ひどい 点でした。", example_reading: "", example_en: "I got a terrible score on yesterday's test.", example_vi: "Bài kiểm tra hôm qua có điểm rất tệ." },
  { page: 150, number: 763, word: "太い", reading: "ふとい", partOfSpeech: "イ形", meaning_vi: "mập, to", meaning_en: "fat, thick", example_ja: "この 大根は とても 太いです。", example_reading: "", example_en: "This Japanese radish is really thick.", example_vi: "Củ cải trắng này rất to." },
  { page: 150, number: 764, word: "細い", reading: "ほそい", partOfSpeech: "イ形", meaning_vi: "ốm, nhỏ, thon", meaning_en: "thin, slender", example_ja: "彼女は 足が とても 細いです。", example_reading: "", example_en: "Her legs are really slender.", example_vi: "Chân cô ấy rất thon." },
  { page: 150, number: 765, word: "厚い", reading: "あつい", partOfSpeech: "イ形", meaning_vi: "dày", meaning_en: "thick", example_ja: "寒いので、厚い コートが ほしいです。", example_reading: "", example_en: "It's cold, so I want a thick coat.", example_vi: "Vì trời lạnh nên tôi muốn có chiếc áo choàng dày." },
  { page: 150, number: 766, word: "あさい", reading: "あさい", partOfSpeech: "イ形", meaning_vi: "nông, cạn", meaning_en: "shallow", example_ja: "この 川は あさいので、子どもも 遊べます。", example_reading: "", example_en: "This river is shallow, so children can play in it.", example_vi: "Con sông này rất cạn nên trẻ con cũng có thể chơi đùa." },

  // Page 151
  { page: 151, number: 767, word: "ふかい", reading: "ふかい", partOfSpeech: "イ形", meaning_vi: "sâu", meaning_en: "deep", example_ja: "この プールの 真ん中は とても ふかいです。", example_reading: "", example_en: "The middle of this pool is very deep.", example_vi: "Chính giữa hồ bơi này rất sâu." },
  { page: 151, number: 768, word: "眠い", reading: "ねむい", partOfSpeech: "イ形", meaning_vi: "buồn ngủ", meaning_en: "sleepy", example_ja: "おなかが いっぱいで、ちょっと 眠いです。", example_reading: "", example_en: "My stomach is full, so I'm a little sleepy.", example_vi: "Tôi no quá nên hơi buồn ngủ." },
  { page: 151, number: 769, word: "めずらしい", reading: "めずらしい", partOfSpeech: "イ形", meaning_vi: "quý hiếm", meaning_en: "rare, uncommon", example_ja: "こんなに 大きな ダイヤは めずらしいです。", example_reading: "", example_en: "A diamond this bog is rare.", example_vi: "Kim cương to như thế này thì thật quý hiếm." },
  { page: 151, number: 770, word: "ふえる", reading: "ふえる", partOfSpeech: "動", meaning_vi: "tăng", meaning_en: "to increase", example_ja: "この 店は 外国の お客さんが とても ふえて います。", example_reading: "", example_en: "The foreign customers in this restaurant are increasing.", example_vi: "Tiệm này khách nước ngoài tăng nhiều." },
  { page: 151, number: 771, word: "ふやす", reading: "ふやす", partOfSpeech: "動", meaning_vi: "làm tăng", meaning_en: "to increase (something)", example_ja: "アルバイトを して、貯金を ふやしたいです。", example_reading: "", example_en: "I want to get a part-time job and increase my savings.", example_vi: "Tôi muốn làm thêm để tăng tiền tiết kiệm." },
  { page: 151, number: 772, word: "へる", reading: "へる", partOfSpeech: "動", meaning_vi: "giảm", meaning_en: "to decrease", example_ja: "日本では 人口が へって います。", example_reading: "", example_en: "In Japan, the population is decreasing.", example_vi: "Ở Nhật dân số đang giảm đi." },
  { page: 151, number: 773, word: "へらす", reading: "へらす", partOfSpeech: "動", meaning_vi: "làm giảm", meaning_en: "to decrease (something)", example_ja: "運動を して、体重を へらしました。", example_reading: "", example_en: "I exercised and decreased my weight.", example_vi: "Tôi đã giảm cân nhờ tập thể dục." },
  { page: 151, number: 774, word: "ちがう", reading: "ちがう", partOfSpeech: "動", meaning_vi: "khác", meaning_en: "to be different, to be wrong", example_ja: "姉と 私は 大学が ちがいます。", example_reading: "", example_en: "My older sister and I go to different colleges.", example_vi: "Chị tôi và tôi (học) khác trường đại học." },

  // Page 152
  { page: 152, number: 775, word: "変える", reading: "かえる", partOfSpeech: "動", meaning_vi: "thay đổi (cái gì đó)", meaning_en: "to change", example_ja: "春に なったら、髪型を 変えます。", example_reading: "", example_en: "I'm going to change my hairstyle when spring comes.", example_vi: "Mùa xuân đến thì tôi đổi kiểu tóc." },
  { page: 152, number: 776, word: "変わる", reading: "かわる", partOfSpeech: "動", meaning_vi: "(cái gì đó) thay đổi", meaning_en: "to be changed", example_ja: "髪を 切ったら、気分が 変わりました。", example_reading: "", example_en: "After getting my hair cut, my mood changed.", example_vi: "Tâm trạng đã thay đổi sau khi cắt tóc." },
  { page: 152, number: 777, word: "見える", reading: "みえる", partOfSpeech: "動", meaning_vi: "thấy được", meaning_en: "to be visible", example_ja: "窓から 富士山が きれいに 見えます。", example_reading: "", example_en: "Mt. Fuji is clearly visible from the window.", example_vi: "Từ cửa sổ có thể nhìn thấy núi Phú Sỹ tuyệt đẹp." },
  { page: 152, number: 778, word: "聞こえる", reading: "きこえる", partOfSpeech: "動", meaning_vi: "nghe được", meaning_en: "to be audible, to be able to hear", example_ja: "近所から 子どもの 声が 聞こえます。", example_reading: "", example_en: "I can hear children's voices from the neighborhood.", example_vi: "Có thể nghe được tiếng trẻ con từ hàng xóm." },
  { page: 152, number: 779, word: "空く", reading: "あく", partOfSpeech: "動", meaning_vi: "trống", meaning_en: "to be vacant", example_ja: "この ホテルは 人気が あって、部屋が 空いて いません。", example_reading: "", example_en: "This hotel is really popular, so it has no vacancies.", example_vi: "Khách sạn này được ưa chuộng nên không có phòng trống." },
  { page: 152, number: 780, word: "はずれる", reading: "はずれる", partOfSpeech: "動", meaning_vi: "(cái gì đó) sút, rời, trật ra", meaning_en: "to come undone", example_ja: "シャツの ボタンが はずれて います。", example_reading: "", example_en: "My shirt button came undone.", example_vi: "Nút áo bị sút." },
  { page: 152, number: 781, word: "切れる", reading: "きれる", partOfSpeech: "動", meaning_vi: "đứt, hết", meaning_en: "to tear, to rip", example_ja: "弟の くつの ひもが 切れました。", example_reading: "", example_en: "My little brother's shoelace ripped.", example_vi: "Dây giày em trai tôi đã đứt rồi." }
];

fs.writeFileSync('scripts/items_part_b.json', JSON.stringify(items_717_781, null, 2));
console.log('Saved items_part_b.json with', items_717_781.length, 'items');
