const fs = require('fs');

const items_782_840 = [
  // Page 156 (Chapter 7, Section 1: ニュース)
  { page: 156, number: 782, word: "新聞社", reading: "しんぶんしゃ", partOfSpeech: "名", meaning_vi: "tòa soạn báo", meaning_en: "newspaper company", example_ja: "来月から 東京の 新聞社で 働きます。", example_reading: "", example_en: "Starting next month, I'll be working at a newspaper company in Tokyo.", example_vi: "Từ tháng sau tôi sẽ làm việc tại tòa soạn báo ở Tokyo." },
  { page: 156, number: 783, word: "テレビ局", reading: "テレビきょく", partOfSpeech: "名", meaning_vi: "đài truyền hình", meaning_en: "TV station", example_ja: "テレビ局の 試験を 受けたいです。", example_reading: "", example_en: "I want to take a test for a TV station.", example_vi: "Tôi muốn dự thi ở đài truyền hình." },
  { page: 156, number: 784, word: "番組", reading: "ばんぐみ", partOfSpeech: "名", meaning_vi: "chương trình", meaning_en: "(TV, radio) program, show", example_ja: "どんな 番組を よく 見ていますか。", example_reading: "", example_en: "What kind of shows are you watching?", example_vi: "Bạn thường xem chương trình (như thế) nào?" },
  { page: 156, number: 785, word: "ネットニュース", reading: "ネットニュース", partOfSpeech: "名", meaning_vi: "tin tức trên mạng", meaning_en: "online news", example_ja: "毎日、ネットニュースを 読んでいます。", example_reading: "", example_en: "I read online news every day.", example_vi: "Hàng ngày tôi xem tin tức trên mạng." },
  { page: 156, number: 786, word: "情報", reading: "じょうほう", partOfSpeech: "名", meaning_vi: "thông tin", meaning_en: "information", example_ja: "インターネットで 世界の 情報が すぐ わかります。", example_reading: "", example_en: "On the Internet, you can find out world news right away.", example_vi: "Có thể biết ngay thông tin thế giới bằng mạng internet." },
  { page: 156, number: 787, word: "データ", reading: "データ", partOfSpeech: "名", meaning_vi: "dữ liệu", meaning_en: "data", example_ja: "世界の データを 集めました。", example_reading: "", example_en: "I gathered data from around the world.", example_vi: "Tôi đã tập hợp dữ liệu của thế giới." },

  // Page 157
  { page: 157, number: 788, word: "キーワード", reading: "キーワード", partOfSpeech: "名", meaning_vi: "từ khóa", meaning_en: "keyword", example_ja: "ニュースの キーワードを メモしましょう。", example_reading: "", example_en: "Let's write down keywords from the news.", example_vi: "Hãy ghi chú lại từ khóa trong bản tin." },
  { page: 157, number: 789, word: "放送〈する〉", reading: "ほうそう", partOfSpeech: "名", meaning_vi: "việc chiếu, phát sóng", meaning_en: "broadcast", example_ja: "この 番組は 海外でも 放送されています。", example_reading: "", example_en: "This program is being broadcast overseas, too.", example_vi: "Chương trình này cũng được phát sóng ở hải ngoại." },
  { page: 157, number: 790, word: "伝える", reading: "つたえる", partOfSpeech: "動", meaning_vi: "truyền đạt", meaning_en: "to convey, to report", example_ja: "むずかしい ニュースを やさしく 伝えます。", example_reading: "", example_en: "They report difficult news in a simple manner.", example_vi: "Truyền đạt tin khó một cách dễ hiểu." },
  { page: 157, number: 791, word: "火事", reading: "かじ", partOfSpeech: "名", meaning_vi: "hỏa hoạn", meaning_en: "fire", example_ja: "駅の 近くで 火事が ありました。", example_reading: "", example_en: "There was a fire near the station.", example_vi: "Đã có hỏa hoạn gần nhà ga." },
  { page: 157, number: 792, word: "（事故が）起こる", reading: "じこがおこる", partOfSpeech: "動", meaning_vi: "(tai nạn) xảy ra", meaning_en: "to break out (fire)", example_ja: "この 道では よく 事故が 起こります。", example_reading: "", example_en: "There are many accidents on this road.", example_vi: "Con đường này thường xảy ra tai nạn." },
  { page: 157, number: 793, word: "発見〈する〉", reading: "はっけん", partOfSpeech: "名", meaning_vi: "việc phát hiện, tìm thấy", meaning_en: "discovery", example_ja: "小学生が 新しい 星を 発見しました。", example_reading: "", example_en: "An elementary school student discovered a new star.", example_vi: "Học sinh tiểu học đã phát hiện ra ngôi sao mới." },
  { page: 157, number: 794, word: "見つかる", reading: "みつかる", partOfSpeech: "動", meaning_vi: "được tìm ra, tìm thấy", meaning_en: "to be found", example_ja: "電車に わすれた 書類が 見つかりました。", example_reading: "", example_en: "I found the documents I left on the train.", example_vi: "Tài liệu để quên trên tàu điện đã được tìm thấy." },
  { page: 157, number: 795, word: "見つける", reading: "みつける", partOfSpeech: "動", meaning_vi: "tìm thấy", meaning_en: "to find", example_ja: "いなくなった 犬を 公園で 見つけました。", example_reading: "", example_en: "I found the dog that went missing in the park.", example_vi: "Tôi đã tìm ra con chó biến mất ở công viên." },

  // Page 158
  { page: 158, number: 796, word: "発表〈する〉", reading: "はっぴょう", partOfSpeech: "名", meaning_vi: "bài phát biểu, việc công bố", meaning_en: "announcement", example_ja: "大好きな 作家が 新しい 小説を 発表しました。", example_reading: "", example_en: "My favorite author announced the release of a new novel.", example_vi: "Tác giả tôi rất yêu thích đã công bố tiểu thuyết mới." },
  { page: 158, number: 797, word: "スピーチ〈する〉", reading: "スピーチ", partOfSpeech: "名", meaning_vi: "diễn văn", meaning_en: "speech", example_ja: "大統領の スピーチは すばらしかったです。", example_reading: "", example_en: "The president's speech was magnificent.", example_vi: "Bài diễn văn của tổng thống thật tuyệt vời." },
  { page: 158, number: 798, word: "つづく", reading: "つづく", partOfSpeech: "動", meaning_vi: "tiếp tục, kéo dài", meaning_en: "to be continued", example_ja: "雨の 日が ２週間も つづいています。", example_reading: "", example_en: "Rainy days have continued for two weeks.", example_vi: "Những ngày mưa kéo dài đến những 2 tuần." },
  { page: 158, number: 799, word: "つづける", reading: "つづける", partOfSpeech: "動", meaning_vi: "tiếp tục", meaning_en: "to continue", example_ja: "これからも 日本語の 勉強を つづけるつもりです。", example_reading: "", example_en: "I intend to keep studying Japanese from now on.", example_vi: "Tôi dự định từ nay vẫn sẽ tiếp tục học tiếng Nhật." },

  // Page 159 (Section 2: 約束)
  { page: 159, number: 800, word: "約束〈する〉", reading: "やくそく", partOfSpeech: "名", meaning_vi: "lời hứa", meaning_en: "promise", example_ja: "友だちと 遊びに 行く 約束を しました。", example_reading: "", example_en: "I promised to go play with my friend.", example_vi: "Tôi đã hứa đi chơi với bạn tôi." },
  { page: 159, number: 801, word: "（約束を）守る", reading: "やくそくをまもる", partOfSpeech: "動", meaning_vi: "giữ (lời hứa)", meaning_en: "to keep (a promise)", example_ja: "約束は 守らなければ なりません。", example_reading: "", example_en: "You must keep your promises.", example_vi: "Phải giữ lời hứa." },
  { page: 159, number: 802, word: "（約束を）やぶる", reading: "やくそくをやぶる", partOfSpeech: "動", meaning_vi: "thất (hứa)", meaning_en: "to break (a promise)", example_ja: "約束を やぶるのは よくないですよ。", example_reading: "", example_en: "It's not good to break your promises.", example_vi: "Thất hứa là không tốt đâu đấy." },
  { page: 159, number: 803, word: "間に合う", reading: "まにあう", partOfSpeech: "動", meaning_vi: "kịp giờ, đúng giờ", meaning_en: "to make it in time", example_ja: "タクシーに 乗っても、コンサートに 間に合いません。", example_reading: "", example_en: "I won't make it to the concert in time, even if I take a taxi.", example_vi: "Dù có đi taxi cũng không kịp (giờ) buổi hòa nhạc." },
  { page: 159, number: 804, word: "おくれる", reading: "おくれる", partOfSpeech: "動", meaning_vi: "trễ giờ", meaning_en: "to be late", example_ja: "デートに １時間も おくれました。", example_reading: "", example_en: "I was an hour late to my date.", example_vi: "Tôi đã trễ giờ hẹn cả 1 tiếng đồng hồ." },
  { page: 159, number: 805, word: "キャンセル〈する〉", reading: "キャンセル", partOfSpeech: "名", meaning_vi: "việc hủy bỏ", meaning_en: "cancellation", example_ja: "台風で 旅行を キャンセルしました。", example_reading: "", example_en: "I cancelled my trip due to the typhoon.", example_vi: "Tôi đã hủy chuyến du lịch vì bão." },
  { page: 159, number: 806, word: "わけ", reading: "わけ", partOfSpeech: "名", meaning_vi: "lý do", meaning_en: "reason, explanation", example_ja: "どうして 妹が 泣いているのか、わけが わかりません。", example_reading: "", example_en: "I don't know why my little sister is crying.", example_vi: "Tôi không hiểu lý do tại sao em gái tôi khóc." },

  // Page 160
  { page: 160, number: 807, word: "さそう", reading: "さそう", partOfSpeech: "動", meaning_vi: "mời", meaning_en: "to invite", example_ja: "パーティーに マリアさんも さそいましょう。", example_reading: "", example_en: "Let's invite Maria-san to the party, too.", example_vi: "Hãy mời cả (chị) Maria đến bữa tiệc." },
  { page: 160, number: 808, word: "れんらく〈する〉", reading: "れんらく", partOfSpeech: "名", meaning_vi: "việc liên lạc", meaning_en: "notice, communication", example_ja: "パーティーの 時間を みんなに れんらくします。", example_reading: "", example_en: "I'm going to communicate the time of the party to everyone.", example_vi: "Tôi sẽ liên lạc giờ giấc của bữa tiệc cho mọi người." },
  { page: 160, number: 809, word: "（電話が）ある", reading: "でんわがある", partOfSpeech: "動", meaning_vi: "có (điện thoại)", meaning_en: "to have a call", example_ja: "国の 友だちから 電話が ありました。", example_reading: "", example_en: "There was a call from my friend from my home country.", example_vi: "Tôi đã có điện thoại từ bạn trong nước." },
  { page: 160, number: 810, word: "食事〈する〉", reading: "しょくじ", partOfSpeech: "名", meaning_vi: "bữa ăn", meaning_en: "meal, dining", example_ja: "来週 みんなで 食事しましょう。", example_reading: "", example_en: "Let's have a meal with everyone next week.", example_vi: "Tuần tới mọi người cùng nhau dùng bữa nào." },
  { page: 160, number: 811, word: "参加〈する〉", reading: "さんか", partOfSpeech: "名", meaning_vi: "sự tham gia", meaning_en: "participation", example_ja: "来週の 社員旅行に 参加します。", example_reading: "", example_en: "I'm going to participate in the employee trip next week.", example_vi: "Tôi sẽ tham gia chuyến du lịch của công ty tuần tới." },
  { page: 160, number: 812, word: "都合", reading: "つごう", partOfSpeech: "名", meaning_vi: "giờ giấc thuận tiện, sự thuận tiện", meaning_en: "convenience, schedule", example_ja: "来週の みなさんの 都合を 教えてください。", example_reading: "", example_en: "Everyone, please tell me your schedules for next week.", example_vi: "Hãy cho biết giờ giấc thuận tiện vào tuần tới của mọi người." },
  { page: 160, number: 813, word: "予定", reading: "よてい", partOfSpeech: "名", meaning_vi: "dự định", meaning_en: "plan", example_ja: "連休には 北海道を 旅行する 予定です。", example_reading: "", example_en: "I plan to take a trip to Hokkaido during the extended weekend.", example_vi: "Tôi dự định đi du lịch Hokkaido dịp nghỉ dài ngày." },
  { page: 160, number: 814, word: "相手", reading: "あいて", partOfSpeech: "名", meaning_vi: "đối phương, người kia", meaning_en: "partner, opponent, person", example_ja: "さっきの 電話の 相手は 母です。", example_reading: "", example_en: "The person who called just now was my mother.", example_vi: "Người nói chuyện điện thoại lúc nãy là mẹ tôi." },

  // Page 161
  { page: 161, number: 815, word: "機会", reading: "きかい", partOfSpeech: "名", meaning_vi: "cơ hội, dịp", meaning_en: "chance, opportunity", example_ja: "このごろ、お酒を 飲む 機会が ふえました。", example_reading: "", example_en: "Nowadays, I have more opportunities to drink alcohol.", example_vi: "Gần đây, những dịp uống rượu tăng lên." },

  // Page 162 (Section 3: 気持ち)
  { page: 162, number: 816, word: "うれしい", reading: "うれしい", partOfSpeech: "イ形", meaning_vi: "vui mừng", meaning_en: "happy, glad", example_ja: "彼に 指輪を もらって、とても うれしいです。", example_reading: "", example_en: "I was really happy to get a ring from him.", example_vi: "Tôi rất vui khi được người yêu tặng nhẫn." },
  { page: 162, number: 817, word: "笑う", reading: "わらう", partOfSpeech: "動", meaning_vi: "cười", meaning_en: "to laugh, to smile", example_ja: "いつも 笑っていれば、いいことが ありますよ。", example_reading: "", example_en: "Something good is bound to happen if you're always smiling.", example_vi: "Nếu lúc nào cũng mỉm cười thì sẽ có việc tốt lành đấy." },
  { page: 162, number: 818, word: "しあわせ〈な〉", reading: "しあわせ", partOfSpeech: "名/ナ形", meaning_vi: "niềm hạnh phúc (hạnh phúc)", meaning_en: "happiness, fortune/fortunate, happy", example_ja: "しあわせは どんな 色だと 思いますか。(名)\n家族 みんな、けんこうで しあわせです。(ナ形)", example_reading: "", example_en: "What color do you think happiness is?\nEveryone in my family is in good health and happy.", example_vi: "Bạn nghĩ hạnh phúc có màu gì?\nMọi người trong gia đình đều mạnh khỏe, hạnh phúc." },
  { page: 162, number: 819, word: "楽な", reading: "らくな", partOfSpeech: "ナ形", meaning_vi: "khỏe, dễ dàng, thoải mái", meaning_en: "easy, comfortable", example_ja: "家で 休むのに 楽な いすが ほしいです。", example_reading: "", example_en: "I want a comfortable chair to rest in at home.", example_vi: "Tôi muốn có một cái ghế thoải mái để nghỉ ngơi tại nhà." },
  { page: 162, number: 820, word: "安心〈な／する〉", reading: "あんしん", partOfSpeech: "名/ナ形", meaning_vi: "sự yên tâm (yên tâm)", meaning_en: "relief/secure, stable", example_ja: "なくした さいふが 見つかって、安心しました。(名)\n友だちが 近くに 住んでいれば、安心です。(ナ形)", example_reading: "", example_en: "I was relieved to find the wallet I had lost.\nIt would be a relief if I had a friend that lived nearby.", example_vi: "Tôi yên tâm khi chiếc ví đánh mất được tìm thấy.\nNếu có bạn sống gần bên thì yên tâm." },

  // Page 163
  { page: 163, number: 821, word: "信じる", reading: "しんじる", partOfSpeech: "動", meaning_vi: "tin, tin tưởng", meaning_en: "to believe, to trust", example_ja: "彼の ことばを 信じて います。", example_reading: "", example_en: "I believe his words.", example_vi: "Tôi tin lời anh ấy." },
  { page: 163, number: 822, word: "祈る", reading: "いのる", partOfSpeech: "動", meaning_vi: "cầu nguyện, cầu chúc", meaning_en: "to pray", example_ja: "世界の 平和を 祈っています。", example_reading: "", example_en: "I pray for world peace.", example_vi: "Tôi nguyện cầu cho hòa bình của thế giới." },
  { page: 163, number: 823, word: "かなしい", reading: "かなしい", partOfSpeech: "イ形", meaning_vi: "buồn bã", meaning_en: "sad", example_ja: "友だちが 帰国して、とても かなしいです。", example_reading: "", example_en: "My friend went back to her home country, so I'm very sad.", example_vi: "Bạn tôi về nước nên tôi rất buồn." },
  { page: 163, number: 824, word: "さびしい", reading: "さびしい", partOfSpeech: "イ形", meaning_vi: "buồn, cô đơn", meaning_en: "lonely", example_ja: "日本へ 来てから １か月くらい とても さびしかったです。", example_reading: "", example_en: "I was so lonely for about a month after I came to Japan.", example_vi: "Khi đến Nhật, khoảng 1 tháng tôi đã rất buồn." },
  { page: 163, number: 825, word: "泣く", reading: "なく", partOfSpeech: "動", meaning_vi: "khóc", meaning_en: "to cry, to weep", example_ja: "電車で 赤ちゃんが 泣いて いました。", example_reading: "", example_en: "A baby was crying on the train.", example_vi: "Em bé khóc trên tàu điện." },
  { page: 163, number: 826, word: "なみだ", reading: "なみだ", partOfSpeech: "名", meaning_vi: "nước mắt", meaning_en: "tear", example_ja: "動物の 映画を 見て、なみだが 出ました。", example_reading: "", example_en: "I saw a movie about animals and cried.", example_vi: "Xem phim động vật tôi đã chảy nước mắt." },
  { page: 163, number: 827, word: "心配〈な／する〉", reading: "しんぱい", partOfSpeech: "名/ナ形", meaning_vi: "sự lo lắng (lo lắng)", meaning_en: "worry, unease/worrisome, uneasy", example_ja: "何も 心配しなくて いいですよ。(名)\n試験に 合格できるかどうか、とても 心配です。(ナ形)", example_reading: "", example_en: "You don't have to worry about anything.\nI'm worried about whether I'll be able to pass the test.", example_vi: "Không phải lo lắng gì cả.\nTôi rất lo lắng không biết có đậu kỳ thi hay không." },

  // Page 164
  { page: 164, number: 828, word: "つまらない", reading: "つまらない", partOfSpeech: "イ形", meaning_vi: "chán, tẻ nhạt", meaning_en: "boring, not interesting", example_ja: "その 映画は つまらなかったです。", example_reading: "", example_en: "That movie was boring.", example_vi: "Bộ phim đó rất chán." },
  { page: 164, number: 829, word: "がっかり〈する〉", reading: "がっかり", partOfSpeech: "副", meaning_vi: "sự thất vọng", meaning_en: "disappointment", example_ja: "好きだった 俳優が 結婚して、がっかりしました。", example_reading: "", example_en: "I was disappointed to hear that an actor that I liked got married.", example_vi: "Diễn viên tôi yêu thích đã kết hôn nên tôi rất thất vọng." },
  { page: 164, number: 830, word: "あきらめる", reading: "あきらめる", partOfSpeech: "動", meaning_vi: "từ bỏ, bỏ cuộc", meaning_en: "to give up", example_ja: "何でも かんたんに あきらめては いけません。", example_reading: "", example_en: "You mustn't give up on everything so easily.", example_vi: "Không được dễ dàng bỏ cuộc bất kỳ điều gì." },
  { page: 164, number: 831, word: "きんちょう〈する〉", reading: "きんちょう", partOfSpeech: "名", meaning_vi: "sự căng thẳng, hồi hộp", meaning_en: "nervousness", example_ja: "きのうの スピーチは とても きんちょうしました。", example_reading: "", example_en: "I was really nervous during my speech yesterday.", example_vi: "Bài hùng biện hôm qua tôi đã rất hồi hộp." },
  { page: 164, number: 832, word: "はずかしい", reading: "はずかしい", partOfSpeech: "イ形", meaning_vi: "mắc cỡ, xấu hổ", meaning_en: "embarrassing, shameful", example_ja: "かんたんな 漢字が 読めなくて、はずかしいです。", example_reading: "", example_en: "I'm embarrassed that I can't read simple kanji.", example_vi: "Tôi xấu hổ khi không thể đọc được những chữ Kanji đơn giản." },
  { page: 164, number: 833, word: "びっくり〈する〉", reading: "びっくり", partOfSpeech: "名", meaning_vi: "sự ngạc nhiên, bất ngờ, giật mình", meaning_en: "surprise", example_ja: "A「田中さんの 家に 1000万円の 皿が あるそうですよ」\nB「えー、それは びっくりですね。」", example_reading: "", example_en: "A: I hear there is a 10,000,000-yen plate at Tanaka-san's house.\nB: What? That's a surprise!", example_vi: "A: Nghe nói ở nhà anh/chị Tanaka có cái đĩa 10 triệu yên đấy.\nB: Hả, nghe giật mình nhỉ." },
  { page: 164, number: 834, word: "おどろく", reading: "おどろく", partOfSpeech: "動", meaning_vi: "giật mình, ngạc nhiên", meaning_en: "to be surprised, to be astonished", example_ja: "夜中に 道で 大きな 声が して、おどろきました。", example_reading: "", example_en: "I was surprised by a loud voice on the street in the middle of the night.", example_vi: "Nửa đêm tôi đã giật mình vì tiếng nói to ở ngoài đường." },
  { page: 164, number: 835, word: "怒る", reading: "おこる", partOfSpeech: "動", meaning_vi: "tức giận, giận dữ", meaning_en: "to get angry", example_ja: "父は 怒ると、顔が 赤く なります。", example_reading: "", example_en: "When my father gets angry, his face turns red.", example_vi: "Cha tôi hễ tức giận thì mặt trở nên đỏ." },

  // Page 165
  { page: 165, number: 836, word: "気分", reading: "きぶん", partOfSpeech: "名", meaning_vi: "tâm trạng, cảm giác", meaning_en: "mood, feeling", example_ja: "早起きした 日は 気分が いいです。", example_reading: "", example_en: "On day when I wake up early, my mood is good.", example_vi: "Ngày nào dậy sớm thì cảm giác sảng khoái." },
  { page: 165, number: 837, word: "気分が悪い", reading: "きぶんがわるい", partOfSpeech: "イ形", meaning_vi: "tâm trạng xấu, cảm giác khó chịu", meaning_en: "bad mood", example_ja: "今朝から 気分が 悪いです。", example_reading: "", example_en: "I've been feeling bad since this morning.", example_vi: "Từ sáng (nay) tôi đã cảm thấy khó chịu." },
  { page: 165, number: 838, word: "心", reading: "こころ", partOfSpeech: "名", meaning_vi: "trái tim, tinh thần, tâm hồn", meaning_en: "heart, mind, spirit", example_ja: "体も 心も けんこうです。", example_reading: "", example_en: "My body and my mind are healthy.", example_vi: "Cả cơ thể lẫn tinh thần đều khỏe mạnh." },
  { page: 165, number: 839, word: "ストレス", reading: "ストレス", partOfSpeech: "名", meaning_vi: "căng thẳng", meaning_en: "stress", example_ja: "ストレスが ない 人は いません。", example_reading: "", example_en: "There is no one who is without stress.", example_vi: "Không có người nào mà không bị căng thẳng." },
  { page: 165, number: 840, word: "ホームシック", reading: "ホームシック", partOfSpeech: "名", meaning_vi: "nhớ nhà", meaning_en: "homesick", example_ja: "ときどき ホームシックで 泣いて います。", example_reading: "", example_en: "Sometimes I get homesick and cry.", example_vi: "Thỉnh thoảng tôi khóc vì nhớ nhà." }
];

fs.writeFileSync('scripts/items_part_c.json', JSON.stringify(items_782_840, null, 2));
console.log('Saved items_part_c.json with', items_782_840.length, 'items');
