const fs = require('fs');

const items_640_716 = [
  // Page 129
  { page: 129, number: 640, word: "ワールドカップ", reading: "ワールドカップ", partOfSpeech: "名", meaning_vi: "giải vô địch thế giới", meaning_en: "World Cup", example_ja: "ワールドカップで 優勝したいです。", example_reading: "", example_en: "I want to win the World Cup.", example_vi: "Tôi muốn vô địch tại giải thế giới." },
  { page: 129, number: 641, word: "行う", reading: "おこなう", partOfSpeech: "動", meaning_vi: "tổ chức", meaning_en: "to hold, to execute", example_ja: "1998年に 日本で 冬の オリンピックが 行われました。", example_reading: "", example_en: "The Winter Olympics were held in Japan in 1998.", example_vi: "Năm 1998 Olympic mùa đông đã được tổ chức tại Nhật Bản." },
  { page: 129, number: 642, word: "中止〈する〉", reading: "ちゅうし", partOfSpeech: "名", meaning_vi: "việc hủy bỏ", meaning_en: "suspension, temporary stoppage", example_ja: "台風が 来たとき、試合は 中止するそうです。", example_reading: "", example_en: "I heard that they are going to suspend the match if a typhoon comes.", example_vi: "Nghe nói nếu bão đến, trận đấu sẽ bị hủy." },
  { page: 129, number: 643, word: "選手", reading: "せんしゅ", partOfSpeech: "名", meaning_vi: "vận động viên", meaning_en: "athlete, player", example_ja: "しょうらい、オリンピックの 選手に なりたいです。", example_reading: "", example_en: "In the future, I want to be an Olympic athlete.", example_vi: "Trong tương lai, tôi muốn trở thành vận động viên Olympic." },
  { page: 129, number: 644, word: "チーム", reading: "チーム", partOfSpeech: "名", meaning_vi: "đội", meaning_en: "team", example_ja: "大好きな チームが 負けて しまいました。", example_reading: "", example_en: "My favorite team lost.", example_vi: "Đội tôi yêu thích đã thua mất rồi." },
  { page: 129, number: 645, word: "勝つ", reading: "かつ", partOfSpeech: "動", meaning_vi: "thắng", meaning_en: "to win", example_ja: "きのうの ゲームは 日本が 勝ちました。", example_reading: "", example_en: "Japan won yesterday's game.", example_vi: "Trận đấu hôm qua Nhật Bản đã thắng." },
  { page: 129, number: 646, word: "優勝〈する〉", reading: "ゆうしょう", partOfSpeech: "名", meaning_vi: "sự vô địch, chức vô địch", meaning_en: "winning a championship", example_ja: "テニスの 大会で 優勝しました。", example_reading: "", example_en: "I won the tennis tournament.", example_vi: "Tôi đã vô địch tại giải quần vợt." },
  { page: 129, number: 647, word: "負ける", reading: "まける", partOfSpeech: "動", meaning_vi: "thua", meaning_en: "to lose", example_ja: "もし 負けても、また 次が あります。", example_reading: "", example_en: "Even if you lose, there's always next time.", example_vi: "Nếu thua vẫn có cơ hội tiếp theo." },

  // Page 130
  { page: 130, number: 648, word: "おうえん〈する〉", reading: "おうえん", partOfSpeech: "名", meaning_vi: "sự ủng hộ", meaning_en: "cheering", example_ja: "好きな チームを おうえんします。", example_reading: "", example_en: "I'm going to cheer for my favorite team.", example_vi: "Tôi sẽ ủng hộ đội mình yêu thích." },
  { page: 130, number: 649, word: "コース", reading: "コース", partOfSpeech: "名", meaning_vi: "lộ trình, khóa", meaning_en: "course", example_ja: "私の ジョギングの コースは ５キロです。", example_reading: "", example_en: "My jogging course is five kilometers.", example_vi: "Lộ trình chạy bộ của tôi là 5 km." },
  { page: 130, number: 650, word: "会場", reading: "かいじょう", partOfSpeech: "名", meaning_vi: "hội trường, nơi thi đấu, nơi tổ chức", meaning_en: "venue, meeting place", example_ja: "剣道の 会場は こちらです。", example_reading: "", example_en: "The kendo venue is over here.", example_vi: "Hội trường kiếm đạo là ở đây." },
  { page: 130, number: 651, word: "スタート〈する〉", reading: "スタート", partOfSpeech: "名", meaning_vi: "điểm xuất phát, sự xuất phát", meaning_en: "start", example_ja: "選手が いっしょに スタートしました。", example_reading: "", example_en: "The athletes started together.", example_vi: "Các vận động viên đã cùng nhau xuất phát." },
  { page: 130, number: 652, word: "失敗〈する〉", reading: "しっぱい", partOfSpeech: "名", meaning_vi: "sự thất bại", meaning_en: "failure, mistake", example_ja: "もし 失敗しても、また がんばれば いいです。", example_reading: "", example_en: "If you make a mistake, just try again.", example_vi: "Nếu thất bại thì lại cố gắng là được." },
  { page: 130, number: 653, word: "柔道", reading: "じゅうどう", partOfSpeech: "名", meaning_vi: "Judo (nhu đạo)", meaning_en: "judo", example_ja: "柔道は 日本で 生まれた スポーツです。", example_reading: "", example_en: "Judo is a sport that was born in Japan.", example_vi: "Judo là môn thể thao ra đời ở Nhật Bản." },
  { page: 130, number: 654, word: "水泳", reading: "すいえい", partOfSpeech: "名", meaning_vi: "bơi lội", meaning_en: "swimming", example_ja: "子どもの とき、水泳が きらいでした。", example_reading: "", example_en: "I hated swimming when I was a child.", example_vi: "Khi còn nhỏ, tôi ghét bơi lội." },
  { page: 130, number: 655, word: "野球", reading: "やきゅう", partOfSpeech: "名", meaning_vi: "bóng chày", meaning_en: "baseball", example_ja: "野球は 日本で 人気の スポーツです。", example_reading: "", example_en: "Baseball is a popular sport in Japan.", example_vi: "Bóng chày là môn thể thao được yêu thích tại Nhật Bản." },

  // Page 131
  { page: 131, number: 656, word: "投げる", reading: "なげる", partOfSpeech: "動", meaning_vi: "ném", meaning_en: "to throw", example_ja: "彼が 投げる ボールは とても 速いです。", example_reading: "", example_en: "The balls he throws are really fast.", example_vi: "Bóng anh ấy ném ra rất nhanh." },
  { page: 131, number: 657, word: "スポーツクラブ", reading: "スポーツクラブ", partOfSpeech: "名", meaning_vi: "câu lạc bộ thể thao", meaning_en: "sports club", example_ja: "うちの 近くの スポーツクラブは 安くて 便利です。", example_reading: "", example_en: "The sports club near my house is inexpensive and convenient.", example_vi: "Câu lạc bộ thể thao gần nhà tôi rẻ và tiện lợi." },

  // Page 134 (Chapter 6, Section 1: 体・けんこう)
  { page: 134, number: 658, word: "髪", reading: "かみ", partOfSpeech: "名", meaning_vi: "tóc", meaning_en: "hair (on one's head)", example_ja: "山田さんは 髪が 長いです。", example_reading: "", example_en: "Yamada-san's hair is long.", example_vi: "Tóc chị Yamada dài." },
  { page: 134, number: 659, word: "おでこ", reading: "おでこ", partOfSpeech: "名", meaning_vi: "trán", meaning_en: "forehead", example_ja: "熱が あるとき、おでこを 冷やします。", example_reading: "", example_en: "When you have a fever, you should cool your forehead.", example_vi: "Khi bị sốt thì làm mát trán." },
  { page: 134, number: 660, word: "あご", reading: "あご", partOfSpeech: "名", meaning_vi: "cằm", meaning_en: "chin, jaw", example_ja: "ガムを かむのは あごに いいそうです。", example_reading: "", example_en: "I hear that chewing gum is good for your jaw.", example_vi: "Nghe nói nhai kẹo cao su tốt cho cằm." },
  { page: 134, number: 661, word: "ひげ", reading: "ひげ", partOfSpeech: "名", meaning_vi: "râu", meaning_en: "facial hair", example_ja: "父は 若いとき、ひげが ありました。", example_reading: "", example_en: "My father had facial hair when he was young.", example_vi: "Khi còn trẻ, cha tôi có râu." },
  { page: 134, number: 662, word: "くちびる", reading: "くちびる", partOfSpeech: "名", meaning_vi: "môi", meaning_en: "lip", example_ja: "彼女の くちびるは とても かわいいです。", example_reading: "", example_en: "Her lips are really cute.", example_vi: "Môi cô ấy rất dễ thương." },
  { page: 134, number: 663, word: "首", reading: "くび", partOfSpeech: "名", meaning_vi: "cổ", meaning_en: "neck", example_ja: "朝起きたら、首が 痛かったです。", example_reading: "", example_en: "When I woke up, my neck hurt.", example_vi: "Buổi sáng khi thức dậy thì cổ tôi bị đau." },
  { page: 134, number: 664, word: "のど", reading: "のど", partOfSpeech: "名", meaning_vi: "cổ họng", meaning_en: "throat", example_ja: "のどに いい 薬は ありますか。", example_reading: "", example_en: "Do you have any good medicine for the throat?", example_vi: "Có thuốc tốt cho cổ họng không?" },

  // Page 135
  { page: 135, number: 665, word: "肩", reading: "かた", partOfSpeech: "名", meaning_vi: "vai", meaning_en: "shoulder", example_ja: "肩が 痛いです。", example_reading: "", example_en: "My shoulder hurts.", example_vi: "Hãy thử ấn vào chỗ này trên vai xem." },
  { page: 135, number: 666, word: "うで", reading: "うで", partOfSpeech: "名", meaning_vi: "cánh tay", meaning_en: "arm", example_ja: "うでを 回してください。", example_reading: "", example_en: "Please rotate your arms.", example_vi: "Hãy xoay cánh tay." },
  { page: 135, number: 667, word: "ひじ", reading: "ひじ", partOfSpeech: "名", meaning_vi: "cùi chỏ, khuỷu tay", meaning_en: "elbow", example_ja: "右の ひじが 赤く なっています。", example_reading: "", example_en: "My right elbow is red.", example_vi: "Cùi chỏ bên phải trở nên đỏ." },
  { page: 135, number: 668, word: "背中", reading: "せなか", partOfSpeech: "名", meaning_vi: "lưng", meaning_en: "back", example_ja: "背中を まっすぐに してください。", example_reading: "", example_en: "Please straighten your back.", example_vi: "Hãy thẳng lưng." },
  { page: 135, number: 669, word: "胃", reading: "い", partOfSpeech: "名", meaning_vi: "dạ dày", meaning_en: "stomach", example_ja: "ごはんを 食べすぎて、胃が 痛いです。", example_reading: "", example_en: "I ate too much, and now my stomach hurts.", example_vi: "Vì ăn cơm quá nhiều nên tôi đau dạ dày." },
  { page: 135, number: 670, word: "こし", reading: "こし", partOfSpeech: "名", meaning_vi: "thắt lưng", meaning_en: "waist, hip, lower back", example_ja: "こしが 痛くて、歩けません。", example_reading: "", example_en: "My lower back hurts so much I can't walk.", example_vi: "Thắt lưng đau đến không thể đi được." },
  { page: 135, number: 671, word: "ひざ", reading: "ひざ", partOfSpeech: "名", meaning_vi: "đầu gối", meaning_en: "knee", example_ja: "走ったら、ひざの 調子が 悪くなりました。", example_reading: "", example_en: "After running, my knees got sore.", example_vi: "Sau khi chạy thì tình trạng đầu gối trở nên xấu đi." },
  { page: 135, number: 672, word: "［お］しり", reading: "おしり", partOfSpeech: "名", meaning_vi: "mông", meaning_en: "butt", example_ja: "ずっと 座っていたので、おしりが 痛いです。", example_reading: "", example_en: "I was sitting for a while, so my butt hurts.", example_vi: "Vì ngồi suốt nên bị đau (ê) mông." },

  // Page 136
  { page: 136, number: 673, word: "指", reading: "ゆび", partOfSpeech: "名", meaning_vi: "ngón (tay, chân)", meaning_en: "finger", example_ja: "バレーボールで 指の 骨を 折りました。", example_reading: "", example_en: "I broke a bone in my finger playing volleyball.", example_vi: "Tôi gãy xương ngón tay vì chơi bóng chuyền." },
  { page: 136, number: 674, word: "つめ", reading: "つめ", partOfSpeech: "名", meaning_vi: "móng", meaning_en: "nail", example_ja: "毎日、つめを きれいに みがきます。", example_reading: "", example_en: "I neatly polish my nails every day.", example_vi: "Hàng ngày tôi chải móng cho sạch." },
  { page: 136, number: 675, word: "骨", reading: "ほね", partOfSpeech: "名", meaning_vi: "xương", meaning_en: "bone", example_ja: "カルシウムは 骨に いいそうです。", example_reading: "", example_en: "I hear calcium is good for the bones.", example_vi: "Nghe nói calcium tốt cho xương." },
  { page: 136, number: 676, word: "血", reading: "ち", partOfSpeech: "名", meaning_vi: "máu", meaning_en: "blood", example_ja: "すべって、足から 血が 出ました。", example_reading: "", example_en: "I slipped and my foot started bleeding.", example_vi: "Tôi đã bị trượt và chảy máu chân." },
  { page: 136, number: 677, word: "力", reading: "ちから", partOfSpeech: "名", meaning_vi: "lực, sức mạnh", meaning_en: "strength, power", example_ja: "私より 妹の ほうが 力が あります。", example_reading: "", example_en: "My younger sister has more strength than I do.", example_vi: "So với tôi, em gái có sức mạnh hơn." },
  { page: 136, number: 678, word: "身長", reading: "しんちょう", partOfSpeech: "名", meaning_vi: "chiều cao", meaning_en: "height", example_ja: "1年で 身長が 10センチも 高く なりました。", example_reading: "", example_en: "My height increased by 10 centimeters in one year.", example_vi: "Trong một năm chiều cao đã tăng lên những 10 cm." },
  { page: 136, number: 679, word: "体重", reading: "たいじゅう", partOfSpeech: "名", meaning_vi: "cân nặng", meaning_en: "weight", example_ja: "毎日、体重を チェックしています。", example_reading: "", example_en: "I check my weight every day.", example_vi: "Tôi kiểm tra cân nặng hàng ngày." },
  { page: 136, number: 680, word: "女性", reading: "じょせい", partOfSpeech: "名", meaning_vi: "nữ giới, phụ nữ", meaning_en: "woman", example_ja: "私が 行く 病院の 先生は 女性です。", example_reading: "", example_en: "The doctor at the hospital I go to is a woman.", example_vi: "Bác sỹ bệnh viện tôi đi là phụ nữ." },

  // Page 137
  { page: 137, number: 681, word: "男性", reading: "だんせい", partOfSpeech: "名", meaning_vi: "nam giới, đàn ông", meaning_en: "man", example_ja: "男性の トイレは ２階に あります。", example_reading: "", example_en: "The men's bathroom is on the second floor.", example_vi: "Nhà vệ sinh nam ở tầng 2." },
  { page: 137, number: 682, word: "けんこう〈な〉", reading: "けんこう", partOfSpeech: "名/ナ形", meaning_vi: "sức khỏe (khỏe mạnh)", meaning_en: "health; healthy", example_ja: "けんこうの ために 野菜を 食べています。(名)\nけんこうな 体を つくろう。(ナ形)", example_reading: "", example_en: "I'm eating vegetables for my health.\nLet's build a healthy body.", example_vi: "Tôi ăn rau vì sức khỏe.\nHãy tạo nên một cơ thể khỏe mạnh." },
  { page: 137, number: 683, word: "じょうぶな", reading: "じょうぶな", partOfSpeech: "ナ形", meaning_vi: "bền, chắc, khỏe", meaning_en: "healthy", example_ja: "運動したら、体が じょうぶに なりました。", example_reading: "", example_en: "Once I started exercising, my body got more healthy.", example_vi: "Tôi tập thể dục thì cơ thể trở nên chắc khỏe lên." },
  { page: 137, number: 684, word: "ビタミン", reading: "ビタミン", partOfSpeech: "名", meaning_vi: "vitamin", meaning_en: "vitamin", example_ja: "この 食事は ビタミンが 足りません。", example_reading: "", example_en: "There aren't enough vitamins in this meal.", example_vi: "Bữa ăn này không đủ vitamin." },
  { page: 137, number: 685, word: "太る", reading: "ふとる", partOfSpeech: "動", meaning_vi: "mập, béo", meaning_en: "to gain weight", example_ja: "寝る前に 食べたので、太って しまいました。", example_reading: "", example_en: "I ate before I went to sleep, so I gained weight.", example_vi: "Vì tôi ăn trước khi ngủ nên mập lên mất rồi." },
  { page: 137, number: 686, word: "やせる", reading: "やせる", partOfSpeech: "動", meaning_vi: "ốm, gầy", meaning_en: "to lose weight", example_ja: "運動しても、なかなか やせません。", example_reading: "", example_en: "I can't lose weight even if I exercise.", example_vi: "Dù có tập thể dục tôi mãi vẫn không thể ốm đi được." },
  { page: 137, number: 687, word: "ダイエット〈する〉", reading: "ダイエット", partOfSpeech: "名", meaning_vi: "việc ăn kiêng", meaning_en: "diet", example_ja: "むりな ダイエットは やめましょう。", example_reading: "", example_en: "Let's not go on any impossible diets.", example_vi: "Hãy dừng việc ăn kiêng quá độ." },

  // Page 138
  { page: 138, number: 688, word: "やめる", reading: "やめる", partOfSpeech: "動", meaning_vi: "ngưng, bỏ", meaning_en: "to stop, to quit", example_ja: "父は 先月から たばこを やめました。", example_reading: "", example_en: "My father quit smoking last month.", example_vi: "Cha tôi bỏ thuốc lá từ tháng trước." },
  { page: 138, number: 689, word: "気をつける", reading: "きをつける", partOfSpeech: "動", meaning_vi: "cẩn thận, giữ gìn", meaning_en: "to be careful", example_ja: "けんこうに 気をつけましょう。", example_reading: "", example_en: "Be care of your health.", example_vi: "Hãy giữ gìn sức khỏe." },
  { page: 138, number: 690, word: "（のどが）かわく", reading: "のどがかわく", partOfSpeech: "動", meaning_vi: "khát, (cổ họng) khô", meaning_en: "to get thirsty", example_ja: "とても のどが かわきました。", example_reading: "", example_en: "I'm really thirsty.", example_vi: "Tôi đã rất khát." },
  { page: 138, number: 691, word: "（おなかが）すく", reading: "おなかがすく", partOfSpeech: "動", meaning_vi: "đói (bụng)", meaning_en: "to get empty (stomach), to get hungry", example_ja: "スポーツを すると、おなかが すきます。", example_reading: "", example_en: "After playing sports, I've gotten hungry.", example_vi: "Hễ chơi thể thao thì đói bụng." },

  // Page 139 (Section 2: 病気・けが)
  { page: 139, number: 692, word: "インフルエンザ", reading: "インフルエンザ", partOfSpeech: "名", meaning_vi: "cúm", meaning_en: "influenza, the flu", example_ja: "インフルエンザで ５日間 学校を 休みました。", example_reading: "", example_en: "I've been absent from school for five days due to the flu.", example_vi: "Tôi đã nghỉ học 5 ngày vì bị cúm." },
  { page: 139, number: 693, word: "かぜをひく", reading: "かぜをひく", partOfSpeech: "動", meaning_vi: "bị cảm", meaning_en: "to catch a cold", example_ja: "子どもの とき、よく かぜを ひきました。", example_reading: "", example_en: "I often caught colds when I was a child.", example_vi: "Khi còn nhỏ tôi thường bị cảm." },
  { page: 139, number: 694, word: "熱", reading: "ねつ", partOfSpeech: "名", meaning_vi: "cơn sốt", meaning_en: "fever", example_ja: "39度も 熱が 出て、学校へ 行けません。", example_reading: "", example_en: "I have a fever of 39 degrees, so I can't go to school.", example_vi: "Tôi sốt đến 39 độ nên không thể đi học." },
  { page: 139, number: 695, word: "体温計", reading: "たいおんけい", partOfSpeech: "名", meaning_vi: "nhiệt kế", meaning_en: "thermometer", example_ja: "体温計で 熱を はかります。", example_reading: "", example_en: "I'm going to take my temperature with a thermometer.", example_vi: "Đo (nhiệt độ) cơn sốt bằng nhiệt kế." },
  { page: 139, number: 696, word: "やけど〈する〉", reading: "やけど", partOfSpeech: "名", meaning_vi: "phỏng", meaning_en: "burn", example_ja: "やかんの おゆで やけどしました。", example_reading: "", example_en: "I burned myself with the hot water in the kettle.", example_vi: "Tôi bị phỏng do nước sôi trong ấm." },
  { page: 139, number: 697, word: "けが〈する〉", reading: "けが", partOfSpeech: "名", meaning_vi: "chấn thương", meaning_en: "injury", example_ja: "サッカーで ひざに けがを しました。", example_reading: "", example_en: "I injured my knee playing soccer.", example_vi: "Tôi bị thương ở đầu gối do đá bóng." },
  { page: 139, number: 698, word: "きず", reading: "きず", partOfSpeech: "名", meaning_vi: "vết thương, vết trầy xước", meaning_en: "wound, cut", example_ja: "この きずは すぐ よくなるでしょう。", example_reading: "", example_en: "I'm sure this wound will get better right away.", example_vi: "Vết thương này sẽ lành mau thôi." },

  // Page 140
  { page: 140, number: 699, word: "調子", reading: "ちょうし", partOfSpeech: "名", meaning_vi: "tình trạng", meaning_en: "condition", example_ja: "胃の 調子が 悪かったので、薬を 飲みました。", example_reading: "", example_en: "My stomach's condition is a little strange, so I took some medicine.", example_vi: "Vì tình trạng dạ dày không tốt nên tôi đã uống thuốc." },
  { page: 140, number: 700, word: "おかしい", reading: "おかしい", partOfSpeech: "イ形", meaning_vi: "kỳ lạ, buồn cười", meaning_en: "strange, funny", example_ja: "おなかの 調子が おかしいので、学校を 休みます。", example_reading: "", example_en: "My stomach's feeling funny, so I'm going to take time off from school.", example_vi: "Vì bụng khó chịu nên tôi nghỉ học." },
  { page: 140, number: 701, word: "具合", reading: "ぐあい", partOfSpeech: "名", meaning_vi: "cảm giác", meaning_en: "condition, status", example_ja: "きのうから 体の 具合が よくないです。", example_reading: "", example_en: "My body's been in bad condition since yesterday.", example_vi: "Từ hôm qua, tình trạng cơ thể tôi không tốt." },
  { page: 140, number: 702, word: "気持ちが悪い", reading: "きもちがわるい", partOfSpeech: "イ形", meaning_vi: "cảm giác khó chịu", meaning_en: "feeling sick, feeling ill", example_ja: "お酒を 飲みすぎて、気持ちが 悪いです。", example_reading: "", example_en: "I drank too much alcohol, and now I feel sick.", example_vi: "Tôi uống quá nhiều rượu nên có cảm giác khó chịu." },
  { page: 140, number: 703, word: "倒れる", reading: "たおれる", partOfSpeech: "動", meaning_vi: "đổ sụp, ngã, đổ, ngã bệnh", meaning_en: "to collapse; to fall down", example_ja: "①地震で 家が 倒れました。\n②きのうの 夜、祖母が 倒れました。", example_reading: "", example_en: "① The house collapsed from the earthquake.\n② My grandmother collapsed last night.", example_vi: "① Nhà cửa đã đổ sụp vì động đất.\n② Tối hôm qua, bà tôi đã ngã bệnh." },
  { page: 140, number: 704, word: "診る", reading: "みる", partOfSpeech: "動", meaning_vi: "khám (bệnh)", meaning_en: "to examine", example_ja: "いつも 近所の お医者さんに 診て もらいます。", example_reading: "", example_en: "I always get examined by the doctor in my neighborhood.", example_vi: "Tôi luôn đi bác sỹ ở gần nhà." },

  // Page 141
  { page: 141, number: 705, word: "（よこに）なる", reading: "よこになる", partOfSpeech: "動", meaning_vi: "nằm xuống, nằm ra", meaning_en: "to lie down", example_ja: "医者「では、そちらに よこに なってください。」", example_reading: "", example_en: "Doctor: Please lie down over there.", example_vi: "Bác sỹ: Nào mời anh/ chị nằm ra kia." },
  { page: 141, number: 706, word: "ぬる", reading: "ぬる", partOfSpeech: "動", meaning_vi: "xức, thoa", meaning_en: "to sleep, to rest", example_ja: "１日に３回、きずに 薬を ぬります。", example_reading: "", example_en: "Apply this medicine to your wound three times a day.", example_vi: "Xức thuốc vào vết thương 1 ngày 3 lần." },
  { page: 141, number: 707, word: "治す", reading: "なおす", partOfSpeech: "動", meaning_vi: "chữa", meaning_en: "to fix, to heal", example_ja: "早く 寝て、かぜを 治して ください。", example_reading: "", example_en: "Please go to sleep early so your cold can heal.", example_vi: "Hãy đi ngủ sớm để trị cảm." },
  { page: 141, number: 708, word: "治る", reading: "なおる", partOfSpeech: "動", meaning_vi: "lành, khỏi bệnh, hết bệnh", meaning_en: "to heal, to recover", example_ja: "薬を 飲んだら、かぜが 治りました。", example_reading: "", example_en: "After taking some medicine, I recovered from my cold.", example_vi: "Sau khi uống thuốc rồi thì tôi đã hết cảm." },
  { page: 141, number: 709, word: "入院〈する〉", reading: "にゅういん", partOfSpeech: "名", meaning_vi: "việc nhập viện", meaning_en: "hospitalization", example_ja: "足の けがで 入院しました。", example_reading: "", example_en: "I was hospitalized due to an injury to my foot.", example_vi: "Tôi đã nhập viện vì bị thương ở chân." },
  { page: 141, number: 710, word: "退院〈する〉", reading: "たいいん", partOfSpeech: "名", meaning_vi: "việc ra viện, xuất viện", meaning_en: "leaving a hospital", example_ja: "病気が 治ったので、明日 退院します。", example_reading: "", example_en: "I've recovered from my illness, so I'm going to leave the hospital tomorrow.", example_vi: "Vì đã hết bệnh nên ngày mai tôi sẽ xuất viện." },
  { page: 141, number: 711, word: "［お］見舞い", reading: "おみまい", partOfSpeech: "名", meaning_vi: "thăm bệnh", meaning_en: "sick visit, visit someone in the hospital", example_ja: "友だちの お見舞いに 行きました。", example_reading: "", example_en: "I went to visit my friend in the hospital.", example_vi: "Tôi đã đi thăm bệnh người bạn." },
  { page: 141, number: 712, word: "生きる", reading: "いきる", partOfSpeech: "動", meaning_vi: "sống", meaning_en: "to live", example_ja: "100さいまで 生きたいです。", example_reading: "", example_en: "I want to live to 100.", example_vi: "Tôi muốn sống đến 100 tuổi." },

  // Page 142
  { page: 142, number: 713, word: "亡くなる", reading: "なくなる", partOfSpeech: "動", meaning_vi: "mất, chết", meaning_en: "to die, to pass away", example_ja: "となりの 家の おばあさんが 亡くなりました。", example_reading: "", example_en: "The elderly woman in the house next door passed away.", example_vi: "Bà cụ nhà bên cạnh đã mất." },
  { page: 142, number: 714, word: "救急車", reading: "きゅうきゅうしゃ", partOfSpeech: "名", meaning_vi: "xe cấp cứu", meaning_en: "ambulance", example_ja: "１１９番で 救急車を よびます。", example_reading: "", example_en: "I'll call 119 and request an ambulance.", example_vi: "Gọi xe cấp cứu bằng số 119." },
  { page: 142, number: 715, word: "歯医者", reading: "はいしゃ", partOfSpeech: "名", meaning_vi: "nha sỹ", meaning_en: "dentist", example_ja: "子どもが 歯医者で 泣いています。", example_reading: "", example_en: "The child is crying at the dentist's.", example_vi: "Đứa bé khóc ở chỗ nha sỹ." },
  { page: 142, number: 716, word: "看護師", reading: "かんごし", partOfSpeech: "名", meaning_vi: "y tá", meaning_en: "nurse", example_ja: "姉は 看護師を しています。", example_reading: "", example_en: "My older sister works as a nurse.", example_vi: "Chị tôi làm y tá." }
];

fs.writeFileSync('scripts/items_part_a.json', JSON.stringify(items_640_716, null, 2));
console.log('Saved items_part_a.json with', items_640_716.length, 'items');
